services:
  db:
    image: postgres:alpine
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - ./postgresql-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres